In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(
    "LnT_Helmet_Survey_Cleaned.csv"
)

df.head()

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
0,1.0,Govind Yadav,19.0,Male,DTU,10/12/2024,Not Mentioned,Always,Two Wheeler,No,Yes,25 KMPH,No,Safety,Always,Very Useful,Standard(ISI Marked),Yes,Yes,18-20
1,2.0,Bhavya,20.0,Male,DTU,10/12/2024,Quality Helmet,Sometime,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Always,Very Useful,Standard(ISI Marked),No,Yes,18-20
2,3.0,Abhishek Kumar,21.0,Male,DTU,11/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Never,Very Useful,Standard(ISI Marked),Yes,No,21-25
3,4.0,Gupreet,20.0,Male,DTU,10/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,30 KMPH,Yes,Safety,Never,Sometime Useful,Standard(ISI Marked),Yes,No,18-20
4,5.0,Mayank Yadav,21.0,Male,DTU,10/12/2024,Not Mentioned,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Never,Sometime Useful,Standard(ISI Marked),No,Yes,21-25

In [5]:
df.shape

(45, 20)

In [17]:
def helemt_score(value):

    if value == "Always":
        return 3

    elif value == "Sometime":
        return 2

    elif value == "Never":
        return 1

    else:
        return 0

In [19]:
df["Helemt_Compliance_Score"] = (
    df["Helemt_Frequency"]
    .apply(helemt_score)
)

In [39]:
df[["Helemt_Frequency", "Helemt_Compliance_Score"]].head()

  Helemt_Frequency  Helemt_Compliance_Score
0           Always                        3
1         Sometime                        2
2           Always                        3
3           Always                        3
4           Always                        3

In [41]:
df["Awareness_Score"] = 0

In [44]:
df.loc[
df["ISI_Awareness"]=="Yes",
"Awareness_Score"
] += 1

In [46]:
df.loc[
df["Helmet_Prevention_belief"]=="Yes",
"Awareness_Score"
] += 1

In [48]:
df["Speed_Limit_Knowledge"].value_counts()

Speed_Limit_Knowledge
25 KMPH    22
30 KMPH    15
40 KMPH     7
60 KMPH     1
Name: count, dtype: int64

In [50]:
df.loc[
df["Speed_Limit_Knowledge"]=="25 KM/H",
"Awareness_Score"
] += 1

In [52]:
df[
[
"ISI_Awareness",
"Helmet_Prevention_belief",
"Awareness_Score"
]
].head()

  ISI_Awareness Helmet_Prevention_belief  Awareness_Score
0            No                       No                0
1            No                      Yes                1
2            No                      Yes                1
3            No                      Yes                1
4            No                      Yes                1

In [62]:
def risk_category(row):

    if (
        row["Helemt_Compliance_Score"] == 3
        and
        row["Awareness_Score"] >= 2
    ):
        return "Safety Champion"


    elif row["Helemt_Compliance_Score"] == 1:
        return "High Risk"


    else:
        return "Moderate Risk"

In [64]:
df["Risk_Category"] = df.apply(
    risk_category,
    axis=1
)

In [66]:
df["Risk_Category"].value_counts()

Risk_Category
Moderate Risk      27
Safety Champion    18
Name: count, dtype: int64

In [70]:
def behaviour_gap(row):

    if (
        row["Awareness_Score"] >=2
        and
        row["Helemt_Compliance_Score"] <=1
    ):
        return "Awareness Without Action"

    else:
        return "Aligned Behaviour"

In [72]:
df["Behaviour_Gap"] = df.apply(
    behaviour_gap,
    axis=1
)

In [74]:
df["Behaviour_Gap"].value_counts()

Behaviour_Gap
Aligned Behaviour           43
Awareness Without Action     2
Name: count, dtype: int64

In [76]:
def age_segment(age):

    if age <=20:
        return "Young Rider"

    elif age <=30:
        return "Adult Rider"

    else:
        return "Experienced Rider"


df["Age_Segment"] = df["Age"].apply(age_segment)

In [78]:
df.to_csv(
"LnT_Safety_Analytics_Final.csv",
index=False
)

In [80]:
import pandas as pd
import re

df = pd.read_csv("LnT_Safety_Analytics_Final.csv")

df.columns = [
    re.sub(r'\W+', '_', c.strip())
    for c in df.columns
]

df.to_csv("LnT_Safety_Analytics_Final_Clean.csv", index=False)